services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    environment:
      - DOZZLE_ENABLE_ACTIONS=true
    restart: unless-stopped
  httpd:
    container_name: httpd
    image: httpd
    ports:
      - "443:443"
    volumes:
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./certs/ca/ca.crt:/usr/local/apache2/certs/ca/ca.crt:ro
      - ./certs/server:/usr/local/apache2/certs/server:ro
      - webdav_data:/usr/local/apache2/dav/
    restart: unless-stopped
  pihole:
    container_name: pihole
    image: pihole/pihole:2024.07.0
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      WEBPASSWORD: '123456'
    volumes:
      - pihole_conf:/etc/pihole
      - pihole_dnsmasq:/etc/dnsmasq.d
    restart: unless-stopped
volumes:
  webdav_data:
    driver: local

  pihole_conf:
    driver: local

  pihole_dnsmasq:
    driver: local
