services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    environment:
      - DOZZLE_ENABLE_ACTIONS=true
  nginx:
    container_name: nginx
    image: nginx 
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs/ca/ca.crt:/etc/nginx/certs/ca/ca.crt:ro
      - ./certs/server:/etc/nginx/certs/server:ro
    restart: unless-stopped
  wsgidav:
    container_name: wsgidav
    # image: mar10/wsgidav # no arm build for now
    build:
      dockerfile: ./wsgidav.Dockerfile
    command:
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "80"
      - "--root"
      - "/var/wsgidav-root"
      - "--auth=anonymous"
      - "--no-config"
    volumes:
      - webdav_data:/var/wsgidav-root/dav
    restart: unless-stopped
  pihole:
    container_name: pihole
    image: pihole/pihole:2024.07.0
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      WEBPASSWORD: '123456'
    volumes:
      -  pihole_conf:/etc/pihole'
    restart: unless-stopped
volumes:
  webdav_data:
    driver: local

  pihole_conf:
    driver: local
