services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    environment:
      - DOZZLE_ENABLE_ACTIONS=true
  nginx:
    container_name: nginx
#    image: nginx # default image does not have the required dav ext module
    build:
      dockerfile: ./nginx.Dockerfile
    ports:
      - "4430:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs/ca/ca.crt:/etc/nginx/certs/ca/ca.crt:ro
      - ./certs/server:/etc/nginx/certs/server:ro
      - webdav_data:/var/www/html/dav/
    restart: unless-stopped

volumes:
  webdav_data:
    driver: local
